// Cleaned location data - duplicates removed
// Generated by LocationDeduplicator on 2025-07-31 20:27:12

export const LOCATIONS_DATA = {
  "10101": [
    {
      "id": 1,
      "name": "Battleground #1",
      "type": "battleground",
      "x": 181,
      "y": 456
    },
    {
      "id": 2,
      "name": "Battleground #2",
      "type": "battleground",
      "x": 105,
      "y": 409
    },
    {
      "id": 3,
      "name": "Battleground #3",
      "type": "battleground",
      "x": 287,
      "y": 405
    },
    {
      "id": 4,
      "name": "Battleground #4",
      "type": "battleground",
      "x": 441,
      "y": 331
    },
    {
      "id": 5,
      "name": "Battleground #5",
      "type": "battleground",
      "x": 529,
      "y": 253
    },
    {
      "id": 6,
      "name": "Battleground #6",
      "type": "battleground",
      "x": 595,
      "y": 279
    },
    {
      "id": 7,
      "name": "Battleground #7",
      "type": "battleground",
      "x": 713,
      "y": 199
    },
    {
      "id": 8,
      "name": "Battleground #8",
      "type": "battleground",
      "x": 661,
      "y": 176
    },
    {
      "id": 9,
      "name": "Battleground #9",
      "type": "battleground",
      "x": 582,
      "y": 123
    },
    {
      "id": 10,
      "name": "Battleground #10",
      "type": "battleground",
      "x": 337,
      "y": 304
    },
    {
      "id": 11,
      "name": "Battleground #11",
      "type": "battleground",
      "x": 335,
      "y": 251
    },
    {
      "id": 12,
      "name": "Battleground #12",
      "type": "battleground",
      "x": 337,
      "y": 185
    },
    {
      "id": 13,
      "name": "Battleground #13",
      "type": "battleground",
      "x": 195,
      "y": 163
    },
    {
      "id": 14,
      "name": "Battleground #14",
      "type": "battleground",
      "x": 118,
      "y": 163
    },
    {
      "id": 15,
      "name": "Battleground #15",
      "type": "battleground",
      "x": 204,
      "y": 106
    },
    {
      "id": 16,
      "name": "Battleground #16",
      "type": "battleground",
      "x": 400,
      "y": 136
    },
    {
      "id": 17,
      "name": "Battleground #17",
      "type": "battleground",
      "x": 399,
      "y": 212
    },
    {
      "id": 18,
      "name": "Battleground #18",
      "type": "battleground",
      "x": 464,
      "y": 212
    },
    {
      "id": 19,
      "name": "Battleground #19",
      "type": "battleground",
      "x": 594,
      "y": 535
    },
    {
      "id": 20,
      "name": "Battleground #20",
      "type": "battleground",
      "x": 661,
      "y": 525
    },
    {
      "id": 21,
      "name": "Foresta",
      "type": "door",
      "x": 240,
      "y": 499
    },
    {
      "id": 22,
      "name": "Forest",
      "type": "door",
      "x": 181,
      "y": 524
    },
    {
      "id": 23,
      "name": "Sand Temple",
      "type": "door",
      "x": 181,
      "y": 396
    },
    {
      "id": 24,
      "name": "Bone Dungeon",
      "type": "door",
      "x": 187,
      "y": 345
    },
    {
      "id": 25,
      "name": "Focus Tower Front Entrance",
      "type": "door",
      "x": 361,
      "y": 433
    },
    {
      "id": 26,
      "name": "Focus Tower Water Exit",
      "type": "door",
      "x": 393,
      "y": 378
    },
    {
      "id": 27,
      "name": "Rope Bridge",
      "type": "door",
      "x": 401,
      "y": 406
    },
    {
      "id": 28,
      "name": "Focus Tower Fire Exit",
      "type": "door",
      "x": 395,
      "y": 349
    },
    {
      "id": 29,
      "name": "Sealed Temple",
      "type": "door",
      "x": 196,
      "y": 214
    },
    {
      "id": 30,
      "name": "Fireburg",
      "type": "door",
      "x": 267,
      "y": 162
    },
    {
      "id": 31,
      "name": "Mine",
      "type": "door",
      "x": 109,
      "y": 105
    },
    {
      "id": 32,
      "name": "Lava Dome",
      "type": "door",
      "x": 310,
      "y": 111
    },
    {
      "id": 33,
      "name": "Volcano",
      "type": "door",
      "x": 323,
      "y": 86
    },
    {
      "id": 34,
      "name": "Libra Temple",
      "type": "door",
      "x": 465,
      "y": 251
    },
    {
      "id": 35,
      "name": "Wintry Temple",
      "type": "door",
      "x": 400,
      "y": 279
    },
    {
      "id": 36,
      "name": "Life Temple",
      "type": "door",
      "x": 517,
      "y": 318
    },
    {
      "id": 37,
      "name": "Aquaria",
      "type": "door",
      "x": 628,
      "y": 225
    },
    {
      "id": 38,
      "name": "Wintry Cave",
      "type": "door",
      "x": 704,
      "y": 148
    },
    {
      "id": 39,
      "name": "Ice Pyramid",
      "type": "door",
      "x": 577,
      "y": 85
    },
    {
      "id": 40,
      "name": "Falls Basin",
      "type": "door",
      "x": 582,
      "y": 189
    },
    {
      "id": 41,
      "name": "Alive Forest",
      "type": "door",
      "x": 492,
      "y": 407
    },
    {
      "id": 42,
      "name": "Kaidge Temple",
      "type": "door",
      "x": 519,
      "y": 534
    },
    {
      "id": 43,
      "name": "Windia",
      "type": "door",
      "x": 691,
      "y": 457
    },
    {
      "id": 44,
      "name": "Pazuzus Tower",
      "type": "door",
      "x": 687,
      "y": 396
    },
    {
      "id": 45,
      "name": "Mount Gale",
      "type": "door",
      "x": 778,
      "y": 474
    },
    {
      "id": 46,
      "name": "Windhole Temple",
      "type": "door",
      "x": 762,
      "y": 525
    },
    {
      "id": 47,
      "name": "Ship Dock",
      "type": "door",
      "x": 636,
      "y": 394
    },
    {
      "id": 48,
      "name": "Spencers Place",
      "type": "door",
      "x": 672,
      "y": 317
    },
    {
      "id": 49,
      "name": "Light Temple",
      "type": "door",
      "x": 427,
      "y": 551
    },
    {
      "id": 50,
      "name": "Doom Castle",
      "type": "door",
      "x": 363,
      "y": 510
    },
    {
      "id": 51,
      "name": "Macs Ship",
      "type": "door",
      "x": 634,
      "y": 368
    }
  ],
  "20102": [
    {
      "id": 52,
      "name": "Box #1",
      "type": "box",
      "x": 441,
      "y": 473
    },
    {
      "id": 53,
      "name": "Kaelis House",
      "type": "door",
      "x": 120,
      "y": 311
    },
    {
      "id": 54,
      "name": "Southern House",
      "type": "door",
      "x": 377,
      "y": 344
    },
    {
      "id": 55,
      "name": "Northern House",
      "type": "door",
      "x": 409,
      "y": 250
    },
    {
      "id": 56,
      "name": "Northern House Back",
      "type": "door",
      "x": 408,
      "y": 187
    },
    {
      "id": 57,
      "name": "Entrance",
      "type": "door",
      "x": 179,
      "y": 410
    }
  ],
  "20103": [
    {
      "id": 58,
      "name": "Box #1",
      "type": "box",
      "x": 135,
      "y": 56
    },
    {
      "id": 59,
      "name": "Entrance",
      "type": "door",
      "x": 133,
      "y": 298
    }
  ],
  "20104": [
    {
      "id": 60,
      "name": "Chest #1",
      "type": "chest",
      "x": 168,
      "y": 71
    },
    {
      "id": 61,
      "name": "Entrance",
      "type": "door",
      "x": 136,
      "y": 314
    },
    {
      "id": 62,
      "name": "Back",
      "type": "door",
      "x": 135,
      "y": 38
    }
  ],
  "20105": [
    {
      "id": 63,
      "name": "Box #1",
      "type": "box",
      "x": 186,
      "y": 54
    },
    {
      "id": 64,
      "name": "Entrance",
      "type": "door",
      "x": 135,
      "y": 296
    }
  ],
  "20202": [
    {
      "id": 65,
      "name": "Box #1",
      "type": "box",
      "x": 166,
      "y": 103
    },
    {
      "id": 66,
      "name": "Box #2",
      "type": "box",
      "x": 535,
      "y": 118
    },
    {
      "id": 67,
      "name": "Box #3",
      "type": "box",
      "x": 362,
      "y": 249
    },
    {
      "id": 68,
      "name": "Box #4",
      "type": "box",
      "x": 453,
      "y": 440
    },
    {
      "id": 69,
      "name": "Box #5",
      "type": "box",
      "x": 153,
      "y": 439
    },
    {
      "id": 70,
      "name": "Entrance",
      "type": "door",
      "x": 338,
      "y": 412
    },
    {
      "id": 71,
      "name": "Exit",
      "type": "door",
      "x": 340,
      "y": 68
    }
  ],
  "20301": [
    {
      "id": 72,
      "name": "Box #1",
      "type": "box",
      "x": 31,
      "y": 189
    },
    {
      "id": 73,
      "name": "Box #2",
      "type": "box",
      "x": 207,
      "y": 189
    },
    {
      "id": 74,
      "name": "Box #3",
      "type": "box",
      "x": 365,
      "y": 192
    },
    {
      "id": 75,
      "name": "Entrance",
      "type": "door",
      "x": 205,
      "y": 364
    },
    {
      "id": 76,
      "name": "Exit",
      "type": "door",
      "x": 206,
      "y": 32
    }
  ],
  "20302": [
    {
      "id": 79,
      "name": "Chest #1",
      "type": "chest",
      "x": 482,
      "y": 44
    },
    {
      "id": 80,
      "name": "Entrance",
      "type": "door",
      "x": 511,
      "y": 460
    },
    {
      "id": 81,
      "name": "Exit",
      "type": "door",
      "x": 85,
      "y": 110
    }
  ],
  "20303": [
    {
      "id": 84,
      "name": "Chest #1",
      "type": "chest",
      "x": 241,
      "y": 72
    },
    {
      "id": 85,
      "name": "Entrance",
      "type": "door",
      "x": 306,
      "y": 383
    },
    {
      "id": 86,
      "name": "Exit",
      "type": "door",
      "x": 47,
      "y": 231
    }
  ],
  "20304": [
    {
      "id": 89,
      "name": "Box #1",
      "type": "box",
      "x": 209,
      "y": 63
    },
    {
      "id": 90,
      "name": "Entrance",
      "type": "door",
      "x": 31,
      "y": 140
    }
  ],
  "20305": [
    {
      "id": 92,
      "name": "Box #1",
      "type": "box",
      "x": 81,
      "y": 315
    },
    {
      "id": 93,
      "name": "Box #2",
      "type": "box",
      "x": 418,
      "y": 427
    },
    {
      "id": 94,
      "name": "Entrance",
      "type": "door",
      "x": 162,
      "y": 411
    },
    {
      "id": 95,
      "name": "Exit",
      "type": "door",
      "x": 495,
      "y": 251
    }
  ],
  "20306": [
    {
      "id": 98,
      "name": "Box #1",
      "type": "box",
      "x": 64,
      "y": 474
    },
    {
      "id": 99,
      "name": "Entrance",
      "type": "door",
      "x": 240,
      "y": 494
    },
    {
      "id": 100,
      "name": "Right",
      "type": "door",
      "x": 255,
      "y": 252
    },
    {
      "id": 101,
      "name": "Left",
      "type": "door",
      "x": 62,
      "y": 189
    },
    {
      "id": 102,
      "name": "Exit",
      "type": "door",
      "x": 159,
      "y": 31
    }
  ],
  "20307": [
    {
      "id": 107,
      "name": "Box #1",
      "type": "box",
      "x": 78,
      "y": 73
    },
    {
      "id": 108,
      "name": "Entrance",
      "type": "door",
      "x": 64,
      "y": 171
    }
  ],
  "20308": [
    {
      "id": 110,
      "name": "Chest #1",
      "type": "chest",
      "x": 62,
      "y": 95
    },
    {
      "id": 111,
      "name": "Entrance",
      "type": "door",
      "x": 68,
      "y": 171
    }
  ],
  "20309": [
    {
      "id": 113,
      "name": "Chest #1",
      "type": "chest",
      "x": 251,
      "y": 78
    },
    {
      "id": 114,
      "name": "Chest #2",
      "type": "chest",
      "x": 32,
      "y": 80
    },
    {
      "id": 115,
      "name": "Box #1",
      "type": "box",
      "x": 31,
      "y": 61
    },
    {
      "id": 116,
      "name": "Box #2",
      "type": "box",
      "x": 32,
      "y": 98
    },
    {
      "id": 117,
      "name": "Entrance",
      "type": "door",
      "x": 158,
      "y": 235
    }
  ],
  "20501": [
    {
      "id": 119,
      "name": "Chest #1",
      "type": "chest",
      "x": 152,
      "y": 55
    },
    {
      "id": 120,
      "name": "Entrance",
      "type": "door",
      "x": 136,
      "y": 396
    }
  ],
  "30102": [
    {
      "id": 122,
      "name": "Entrance",
      "type": "door",
      "x": 142,
      "y": 558
    },
    {
      "id": 123,
      "name": "Exit",
      "type": "door",
      "x": 46,
      "y": 256
    },
    {
      "id": 124,
      "name": "Exit 3",
      "type": "door",
      "x": 361,
      "y": 540
    },
    {
      "id": 125,
      "name": "Entrance 2",
      "type": "door",
      "x": 268,
      "y": 316
    },
    {
      "id": 126,
      "name": "Exit 2",
      "type": "door",
      "x": 271,
      "y": 378
    },
    {
      "id": 127,
      "name": "Entrance 3",
      "type": "door",
      "x": 399,
      "y": 154
    }
  ],
  "30103": [
    {
      "id": 134,
      "name": "Entrance",
      "type": "door",
      "x": 56,
      "y": 342
    },
    {
      "id": 135,
      "name": "Water Exit",
      "type": "door",
      "x": 250,
      "y": 41
    },
    {
      "id": 136,
      "name": "Fire Exit",
      "type": "door",
      "x": 248,
      "y": 136
    },
    {
      "id": 137,
      "name": "Wind Exit",
      "type": "door",
      "x": 392,
      "y": 437
    },
    {
      "id": 138,
      "name": "Doom Entrance",
      "type": "door",
      "x": 247,
      "y": 436
    },
    {
      "id": 139,
      "name": "Doom Exit",
      "type": "door",
      "x": 246,
      "y": 360
    },
    {
      "id": 140,
      "name": "Box #1",
      "type": "box",
      "x": 151,
      "y": 342
    }
  ],
  "30104": [
    {
      "id": 148,
      "name": "Chest #1",
      "type": "chest",
      "x": 327,
      "y": 137
    },
    {
      "id": 149,
      "name": "Chest #2",
      "type": "chest",
      "x": 120,
      "y": 296
    },
    {
      "id": 150,
      "name": "Chest #3",
      "type": "chest",
      "x": 183,
      "y": 330
    },
    {
      "id": 151,
      "name": "Entrance 1",
      "type": "door",
      "x": 375,
      "y": 201
    },
    {
      "id": 152,
      "name": "Entrance 2",
      "type": "door",
      "x": 231,
      "y": 216
    },
    {
      "id": 153,
      "name": "Exit 2",
      "type": "door",
      "x": 87,
      "y": 204
    },
    {
      "id": 154,
      "name": "Entrance 3",
      "type": "door",
      "x": 233,
      "y": 91
    },
    {
      "id": 155,
      "name": "Exit 3",
      "type": "door",
      "x": 265,
      "y": 39
    }
  ],
  "30105": [
    {
      "id": 161,
      "name": "Box #1",
      "type": "box",
      "x": 104,
      "y": 281
    },
    {
      "id": 162,
      "name": "Entrance",
      "type": "door",
      "x": 42,
      "y": 201
    },
    {
      "id": 163,
      "name": "Exit",
      "type": "door",
      "x": 120,
      "y": 74
    },
    {
      "id": 164,
      "name": "Entrance 2",
      "type": "door",
      "x": 329,
      "y": 201
    },
    {
      "id": 165,
      "name": "Exit 2",
      "type": "door",
      "x": 278,
      "y": 57
    }
  ],
  "40102": [
    {
      "id": 170,
      "name": "Entrance",
      "type": "door",
      "x": 386,
      "y": 439
    },
    {
      "id": 171,
      "name": "Inn",
      "type": "door",
      "x": 392,
      "y": 314
    },
    {
      "id": 172,
      "name": "Northwest House",
      "type": "door",
      "x": 106,
      "y": 119
    },
    {
      "id": 173,
      "name": "Phoebe\u0027s House",
      "type": "door",
      "x": 105,
      "y": 344
    },
    {
      "id": 174,
      "name": "Spencers Place",
      "type": "door",
      "x": 132,
      "y": 325
    }
  ],
  "40103": [
    {
      "id": 180,
      "name": "Entrance",
      "type": "door",
      "x": 185,
      "y": 169
    }
  ],
  "40104": [
    {
      "id": 182,
      "name": "Box #1",
      "type": "box",
      "x": 198,
      "y": 56
    },
    {
      "id": 183,
      "name": "Entrance",
      "type": "door",
      "x": 122,
      "y": 167
    },
    {
      "id": 184,
      "name": "Basement",
      "type": "door",
      "x": 25,
      "y": 73
    }
  ],
  "40105": [
    {
      "id": 187,
      "name": "Entrance",
      "type": "door",
      "x": 71,
      "y": 55
    },
    {
      "id": 188,
      "name": "Crest",
      "type": "door",
      "x": 36,
      "y": 73
    }
  ],
  "40106": [
    {
      "id": 191,
      "name": "Box #1",
      "type": "box",
      "x": 118,
      "y": 89
    },
    {
      "id": 192,
      "name": "Entrance",
      "type": "door",
      "x": 182,
      "y": 199
    }
  ],
  "40201": [
    {
      "id": 194,
      "name": "Box #1",
      "type": "box",
      "x": 593,
      "y": 303
    },
    {
      "id": 195,
      "name": "Chest #1",
      "type": "chest",
      "x": 883,
      "y": 445
    },
    {
      "id": 196,
      "name": "Box #2",
      "type": "box",
      "x": 96,
      "y": 624
    },
    {
      "id": 197,
      "name": "Box #3",
      "type": "box",
      "x": 113,
      "y": 626
    },
    {
      "id": 198,
      "name": "Entrance",
      "type": "door",
      "x": 315,
      "y": 593
    },
    {
      "id": 199,
      "name": "Left Stairs",
      "type": "door",
      "x": 65,
      "y": 448
    },
    {
      "id": 200,
      "name": "Top Stairs",
      "type": "door",
      "x": 514,
      "y": 29
    },
    {
      "id": 201,
      "name": "Right Stairs",
      "type": "door",
      "x": 562,
      "y": 161
    },
    {
      "id": 202,
      "name": "Top Left Stairs",
      "type": "door",
      "x": 194,
      "y": 258
    },
    {
      "id": 203,
      "name": "Top Right Stairs",
      "type": "door",
      "x": 419,
      "y": 277
    }
  ],
  "40202": [
    {
      "id": 204,
      "name": "Box #1",
      "type": "box",
      "x": 178,
      "y": 94
    },
    {
      "id": 205,
      "name": "Box #2",
      "type": "box",
      "x": 384,
      "y": 30
    },
    {
      "id": 206,
      "name": "Box #3",
      "type": "box",
      "x": 114,
      "y": 255
    },
    {
      "id": 207,
      "name": "Box #4",
      "type": "box",
      "x": 177,
      "y": 271
    },
    {
      "id": 208,
      "name": "Box #5",
      "type": "box",
      "x": 498,
      "y": 397
    },
    {
      "id": 209,
      "name": "Box #6",
      "type": "box",
      "x": 482,
      "y": 227
    },
    {
      "id": 210,
      "name": "Left Entrance",
      "type": "door",
      "x": 33,
      "y": 447
    },
    {
      "id": 211,
      "name": "Lower Stairs",
      "type": "door",
      "x": 321,
      "y": 306
    },
    {
      "id": 212,
      "name": "Top Left Entrance",
      "type": "door",
      "x": 114,
      "y": 192
    },
    {
      "id": 213,
      "name": "Upper Stairs",
      "type": "door",
      "x": 164,
      "y": 148
    },
    {
      "id": 214,
      "name": "Middle Entrance",
      "type": "door",
      "x": 321,
      "y": 256
    },
    {
      "id": 215,
      "name": "Top Entrance",
      "type": "door",
      "x": 386,
      "y": 99
    },
    {
      "id": 216,
      "name": "Top Right Stairs",
      "type": "door",
      "x": 483,
      "y": 159
    }
  ],
  "40203": [
    {
      "id": 217,
      "name": "Box #1",
      "type": "box",
      "x": 163,
      "y": 192
    },
    {
      "id": 218,
      "name": "Box #2",
      "type": "box",
      "x": 160,
      "y": 226
    },
    {
      "id": 219,
      "name": "Box #3",
      "type": "box",
      "x": 211,
      "y": 301
    },
    {
      "id": 220,
      "name": "Box #4",
      "type": "box",
      "x": 239,
      "y": 305
    },
    {
      "id": 221,
      "name": "Box #5",
      "type": "box",
      "x": 437,
      "y": 367
    },
    {
      "id": 222,
      "name": "Box #6",
      "type": "box",
      "x": 399,
      "y": 162
    },
    {
      "id": 223,
      "name": "Entrance",
      "type": "door",
      "x": 162,
      "y": 130
    },
    {
      "id": 224,
      "name": "Exit",
      "type": "door",
      "x": 210,
      "y": 99
    },
    {
      "id": 225,
      "name": "Exit 2",
      "type": "door",
      "x": 293,
      "y": 272
    }
  ],
  "40204": [
    {
      "id": 226,
      "name": "Box #1",
      "type": "box",
      "x": 115,
      "y": 142
    },
    {
      "id": 227,
      "name": "Box #2",
      "type": "box",
      "x": 113,
      "y": 223
    },
    {
      "id": 228,
      "name": "Box #3",
      "type": "box",
      "x": 142,
      "y": 226
    },
    {
      "id": 229,
      "name": "Box #4",
      "type": "box",
      "x": 178,
      "y": 287
    },
    {
      "id": 230,
      "name": "Box #5",
      "type": "box",
      "x": 241,
      "y": 290
    },
    {
      "id": 231,
      "name": "Box #6",
      "type": "box",
      "x": 274,
      "y": 223
    },
    {
      "id": 232,
      "name": "Box #7",
      "type": "box",
      "x": 303,
      "y": 225
    },
    {
      "id": 233,
      "name": "Chest #1",
      "type": "chest",
      "x": 273,
      "y": 148
    },
    {
      "id": 234,
      "name": "Entrance",
      "type": "door",
      "x": 210,
      "y": 97
    },
    {
      "id": 235,
      "name": "Exit",
      "type": "door",
      "x": 370,
      "y": 321
    }
  ],
  "40205": [
    {
      "id": 236,
      "name": "Box #1",
      "type": "box",
      "x": 62,
      "y": 97
    },
    {
      "id": 237,
      "name": "Box #2",
      "type": "box",
      "x": 94,
      "y": 99
    },
    {
      "id": 238,
      "name": "Box #3",
      "type": "box",
      "x": 222,
      "y": 77
    },
    {
      "id": 239,
      "name": "Box #4",
      "type": "box",
      "x": 49,
      "y": 190
    },
    {
      "id": 240,
      "name": "Box #5",
      "type": "box",
      "x": 114,
      "y": 305
    },
    {
      "id": 241,
      "name": "Box #6",
      "type": "box",
      "x": 144,
      "y": 305
    },
    {
      "id": 242,
      "name": "Entrance",
      "type": "door",
      "x": 319,
      "y": 353
    },
    {
      "id": 243,
      "name": "Entrance 2",
      "type": "door",
      "x": 79,
      "y": 307
    },
    {
      "id": 244,
      "name": "Exit",
      "type": "door",
      "x": 79,
      "y": 37
    }
  ],
  "40206": [
    {
      "id": 245,
      "name": "Chest #1",
      "type": "chest",
      "x": 194,
      "y": 61
    },
    {
      "id": 246,
      "name": "Entrance",
      "type": "door",
      "x": 63,
      "y": 276
    }
  ],
  "40207": [
    {
      "id": 247,
      "name": "Box #1",
      "type": "box",
      "x": 127,
      "y": 257
    },
    {
      "id": 248,
      "name": "Box #2",
      "type": "box",
      "x": 165,
      "y": 224
    },
    {
      "id": 249,
      "name": "Box #3",
      "type": "box",
      "x": 193,
      "y": 255
    },
    {
      "id": 250,
      "name": "Chest #1",
      "type": "chest",
      "x": 163,
      "y": 287
    },
    {
      "id": 251,
      "name": "Exit",
      "type": "door",
      "x": 52,
      "y": 131
    }
  ],
  "40208": [
    {
      "id": 252,
      "name": "Entrance",
      "type": "door",
      "x": 69,
      "y": 257
    },
    {
      "id": 253,
      "name": "Exit",
      "type": "door",
      "x": 67,
      "y": 29
    }
  ],
  "40301": [
    {
      "id": 254,
      "name": "Chest #1",
      "type": "chest",
      "x": 235,
      "y": 168
    },
    {
      "id": 255,
      "name": "Entrance",
      "type": "door",
      "x": 248,
      "y": 423
    }
  ],
  "40302": [
    {
      "id": 256,
      "name": "Box #1",
      "type": "box",
      "x": 477,
      "y": 103
    }
  ],
  "40401": [
    {
      "id": 257,
      "name": "Box #1",
      "type": "box",
      "x": 805,
      "y": 57
    },
    {
      "id": 258,
      "name": "Box #2",
      "type": "box",
      "x": 770,
      "y": 380
    },
    {
      "id": 259,
      "name": "Box #3",
      "type": "box",
      "x": 467,
      "y": 552
    },
    {
      "id": 260,
      "name": "Box #4",
      "type": "box",
      "x": 641,
      "y": 619
    },
    {
      "id": 261,
      "name": "Entrance",
      "type": "door",
      "x": 770,
      "y": 603
    },
    {
      "id": 262,
      "name": "Exit 1",
      "type": "door",
      "x": 610,
      "y": 73
    },
    {
      "id": 263,
      "name": "Exit 2",
      "type": "door",
      "x": 128,
      "y": 360
    }
  ],
  "40402": [
    {
      "id": 264,
      "name": "Box #1",
      "type": "box",
      "x": 130,
      "y": 233
    },
    {
      "id": 265,
      "name": "Box #2",
      "type": "box",
      "x": 162,
      "y": 266
    },
    {
      "id": 266,
      "name": "Box #3",
      "type": "box",
      "x": 385,
      "y": 264
    },
    {
      "id": 267,
      "name": "Box #4",
      "type": "box",
      "x": 401,
      "y": 263
    },
    {
      "id": 268,
      "name": "Entrance",
      "type": "door",
      "x": 115,
      "y": 314
    },
    {
      "id": 269,
      "name": "Exit",
      "type": "door",
      "x": 434,
      "y": 104
    }
  ],
  "40403": [
    {
      "id": 270,
      "name": "Box #1",
      "type": "box",
      "x": 146,
      "y": 56
    },
    {
      "id": 271,
      "name": "Box #2",
      "type": "box",
      "x": 177,
      "y": 72
    },
    {
      "id": 272,
      "name": "Box #3",
      "type": "box",
      "x": 162,
      "y": 232
    },
    {
      "id": 273,
      "name": "Entrance",
      "type": "door",
      "x": 33,
      "y": 184
    },
    {
      "id": 274,
      "name": "Entrance 2",
      "type": "door",
      "x": 356,
      "y": 105
    }
  ],
  "40501": [
    {
      "id": 275,
      "name": "Entrance",
      "type": "door",
      "x": 317,
      "y": 119
    },
    {
      "id": 276,
      "name": "Exit",
      "type": "door",
      "x": 355,
      "y": 905
    }
  ],
  "40502": [
    {
      "id": 277,
      "name": "Box #1",
      "type": "box",
      "x": 464,
      "y": 215
    },
    {
      "id": 278,
      "name": "Entrance",
      "type": "door",
      "x": 273,
      "y": 377
    },
    {
      "id": 279,
      "name": "Entrance 2",
      "type": "door",
      "x": 256,
      "y": 91
    }
  ],
  "40503": [
    {
      "id": 280,
      "name": "Entrance",
      "type": "door",
      "x": 384,
      "y": 489
    },
    {
      "id": 281,
      "name": "Crest 1",
      "type": "door",
      "x": 205,
      "y": 473
    },
    {
      "id": 282,
      "name": "Crest 2",
      "type": "door",
      "x": 191,
      "y": 364
    },
    {
      "id": 283,
      "name": "Crest 3",
      "type": "door",
      "x": 78,
      "y": 172
    },
    {
      "id": 284,
      "name": "Crest 4",
      "type": "door",
      "x": 477,
      "y": 94
    }
  ],
  "40601": [
    {
      "id": 285,
      "name": "Box #1",
      "type": "box",
      "x": 151,
      "y": 56
    },
    {
      "id": 286,
      "name": "Crest",
      "type": "door",
      "x": 135,
      "y": 119
    },
    {
      "id": 287,
      "name": "Entrance",
      "type": "door",
      "x": 152,
      "y": 234
    }
  ],
  "40701": [
    {
      "id": 288,
      "name": "Box #1",
      "type": "box",
      "x": 169,
      "y": 71
    },
    {
      "id": 289,
      "name": "Entrance",
      "type": "door",
      "x": 152,
      "y": 391
    },
    {
      "id": 290,
      "name": "Crest",
      "type": "door",
      "x": 56,
      "y": 309
    }
  ],
  "40801": [
    {
      "id": 291,
      "name": "Box #1",
      "type": "box",
      "x": 119,
      "y": 154
    },
    {
      "id": 292,
      "name": "Box #2",
      "type": "box",
      "x": 155,
      "y": 133
    },
    {
      "id": 293,
      "name": "Crest",
      "type": "door",
      "x": 155,
      "y": 167
    },
    {
      "id": 294,
      "name": "Entrance",
      "type": "door",
      "x": 138,
      "y": 279
    }
  ],
  "50101": [
    {
      "id": 295,
      "name": "Box #1",
      "type": "box",
      "x": 392,
      "y": 457
    },
    {
      "id": 296,
      "name": "Entrance",
      "type": "door",
      "x": 437,
      "y": 267
    },
    {
      "id": 297,
      "name": "Hotel",
      "type": "door",
      "x": 327,
      "y": 151
    },
    {
      "id": 298,
      "name": "Ruben\u0027s House",
      "type": "door",
      "x": 234,
      "y": 119
    },
    {
      "id": 299,
      "name": "Locked House",
      "type": "door",
      "x": 200,
      "y": 310
    },
    {
      "id": 300,
      "name": "Southwest House",
      "type": "door",
      "x": 169,
      "y": 407
    }
  ],
  "50102": [
    {
      "id": 301,
      "name": "Entrance",
      "type": "door",
      "x": 247,
      "y": 361
    },
    {
      "id": 302,
      "name": "Stairs",
      "type": "door",
      "x": 40,
      "y": 263
    }
  ],
  "50103": [
    {
      "id": 303,
      "name": "Entrance",
      "type": "door",
      "x": 151,
      "y": 150
    }
  ],
  "50104": [
    {
      "id": 304,
      "name": "Box #1",
      "type": "box",
      "x": 167,
      "y": 117
    },
    {
      "id": 305,
      "name": "Entrance",
      "type": "door",
      "x": 119,
      "y": 230
    }
  ],
  "50105": [
    {
      "id": 306,
      "name": "Entrance",
      "type": "door",
      "x": 102,
      "y": 198
    },
    {
      "id": 307,
      "name": "Stairs",
      "type": "door",
      "x": 134,
      "y": 71
    }
  ],
  "50106": [
    {
      "id": 308,
      "name": "Entrance",
      "type": "door",
      "x": 58,
      "y": 133
    },
    {
      "id": 309,
      "name": "Crest",
      "type": "door",
      "x": 55,
      "y": 87
    }
  ],
  "50107": [
    {
      "id": 310,
      "name": "Entrance",
      "type": "door",
      "x": 119,
      "y": 169
    },
    {
      "id": 311,
      "name": "Basement",
      "type": "door",
      "x": 24,
      "y": 74
    }
  ],
  "50108": [
    {
      "id": 312,
      "name": "Entrance",
      "type": "door",
      "x": 70,
      "y": 57
    },
    {
      "id": 313,
      "name": "Crest",
      "type": "door",
      "x": 39,
      "y": 70
    }
  ],
  "50201": [
    {
      "id": 314,
      "name": "Entrance",
      "type": "door",
      "x": 72,
      "y": 803
    },
    {
      "id": 315,
      "name": "Left Exit",
      "type": "door",
      "x": 84,
      "y": 455
    },
    {
      "id": 316,
      "name": "Top Left Exit",
      "type": "door",
      "x": 130,
      "y": 115
    },
    {
      "id": 317,
      "name": "Top Exit",
      "type": "door",
      "x": 418,
      "y": 250
    },
    {
      "id": 318,
      "name": "Middle Exit",
      "type": "door",
      "x": 343,
      "y": 569
    },
    {
      "id": 319,
      "name": "Right Exit",
      "type": "door",
      "x": 933,
      "y": 470
    }
  ],
  "50202": [
    {
      "id": 320,
      "name": "Box #1",
      "type": "box",
      "x": 27,
      "y": 280
    },
    {
      "id": 321,
      "name": "Box #2",
      "type": "box",
      "x": 107,
      "y": 279
    },
    {
      "id": 322,
      "name": "Entrance",
      "type": "door",
      "x": 74,
      "y": 313
    }
  ],
  "50203": [
    {
      "id": 323,
      "name": "Chest #1",
      "type": "chest",
      "x": 61,
      "y": 85
    },
    {
      "id": 324,
      "name": "Entrance",
      "type": "door",
      "x": 91,
      "y": 330
    }
  ],
  "50204": [
    {
      "id": 325,
      "name": "Box #1",
      "type": "box",
      "x": 269,
      "y": 75
    },
    {
      "id": 326,
      "name": "Entrance",
      "type": "door",
      "x": 172,
      "y": 331
    }
  ],
  "50205": [
    {
      "id": 327,
      "name": "Box #1",
      "type": "box",
      "x": 114,
      "y": 117
    },
    {
      "id": 328,
      "name": "Box #2",
      "type": "box",
      "x": 177,
      "y": 88
    },
    {
      "id": 329,
      "name": "Box #3",
      "type": "box",
      "x": 207,
      "y": 86
    },
    {
      "id": 330,
      "name": "Box #4",
      "type": "box",
      "x": 193,
      "y": 134
    },
    {
      "id": 331,
      "name": "Entrance",
      "type": "door",
      "x": 129,
      "y": 91
    }
  ],
  "50301": [
    {
      "id": 332,
      "name": "Box #1",
      "type": "box",
      "x": 35,
      "y": 151
    },
    {
      "id": 333,
      "name": "Box #2",
      "type": "box",
      "x": 533,
      "y": 371
    },
    {
      "id": 334,
      "name": "Box #3",
      "type": "box",
      "x": 563,
      "y": 371
    },
    {
      "id": 335,
      "name": "Entrance",
      "type": "door",
      "x": 334,
      "y": 403
    },
    {
      "id": 336,
      "name": "Left Exit",
      "type": "door",
      "x": 277,
      "y": 6
    },
    {
      "id": 337,
      "name": "Right Exit",
      "type": "door",
      "x": 474,
      "y": 6
    }
  ],
  "50302": [
    {
      "id": 338,
      "name": "Box #1",
      "type": "box",
      "x": 327,
      "y": 100
    },
    {
      "id": 339,
      "name": "Box #2",
      "type": "box",
      "x": 390,
      "y": 85
    },
    {
      "id": 340,
      "name": "Right Entrance",
      "type": "door",
      "x": 374,
      "y": 219
    },
    {
      "id": 341,
      "name": "Left Entrance",
      "type": "door",
      "x": 181,
      "y": 229
    },
    {
      "id": 342,
      "name": "Left Exit",
      "type": "door",
      "x": 250,
      "y": 4
    },
    {
      "id": 343,
      "name": "Right Exit",
      "type": "door",
      "x": 438,
      "y": 8
    }
  ],
  "50303": [
    {
      "id": 344,
      "name": "Box #1",
      "type": "box",
      "x": 314,
      "y": 102
    },
    {
      "id": 345,
      "name": "Left Entrance",
      "type": "door",
      "x": 186,
      "y": 364
    },
    {
      "id": 346,
      "name": "Right Entrance",
      "type": "door",
      "x": 280,
      "y": 267
    },
    {
      "id": 347,
      "name": "Left Exit",
      "type": "door",
      "x": 153,
      "y": 5
    },
    {
      "id": 348,
      "name": "Right Exit",
      "type": "door",
      "x": 281,
      "y": 7
    }
  ],
  "50304": [
    {
      "id": 349,
      "name": "Box #1",
      "type": "box",
      "x": 75,
      "y": 125
    },
    {
      "id": 350,
      "name": "Box #2",
      "type": "box",
      "x": 327,
      "y": 108
    },
    {
      "id": 351,
      "name": "Box #3",
      "type": "box",
      "x": 375,
      "y": 139
    },
    {
      "id": 352,
      "name": "Left Entrance",
      "type": "door",
      "x": 134,
      "y": 377
    },
    {
      "id": 353,
      "name": "Right Entrance",
      "type": "door",
      "x": 325,
      "y": 376
    },
    {
      "id": 354,
      "name": "Exit",
      "type": "door",
      "x": 198,
      "y": 75
    }
  ],
  "50401": [
    {
      "id": 355,
      "name": "Box #1",
      "type": "box",
      "x": 789,
      "y": 196
    },
    {
      "id": 356,
      "name": "Box #2",
      "type": "box",
      "x": 996,
      "y": 360
    },
    {
      "id": 357,
      "name": "Box #3",
      "type": "box",
      "x": 503,
      "y": 419
    },
    {
      "id": 358,
      "name": "Box #4",
      "type": "box",
      "x": 5,
      "y": 423
    },
    {
      "id": 359,
      "name": "Entrance",
      "type": "door",
      "x": 784,
      "y": 86
    },
    {
      "id": 360,
      "name": "Door #1",
      "type": "door",
      "x": 490,
      "y": 85
    },
    {
      "id": 361,
      "name": "Door #2",
      "type": "door",
      "x": 776,
      "y": 183
    },
    {
      "id": 362,
      "name": "Door #3",
      "type": "door",
      "x": 906,
      "y": 277
    },
    {
      "id": 363,
      "name": "Door #4",
      "type": "door",
      "x": 444,
      "y": 311
    },
    {
      "id": 364,
      "name": "Door #5",
      "type": "door",
      "x": 450,
      "y": 371
    },
    {
      "id": 365,
      "name": "Door #6",
      "type": "door",
      "x": 392,
      "y": 186
    },
    {
      "id": 366,
      "name": "Door #7",
      "type": "door",
      "x": 267,
      "y": 150
    },
    {
      "id": 367,
      "name": "Door #8",
      "type": "door",
      "x": 260,
      "y": 249
    },
    {
      "id": 368,
      "name": "Door #9",
      "type": "door",
      "x": 106,
      "y": 87
    },
    {
      "id": 369,
      "name": "Door #10",
      "type": "door",
      "x": 105,
      "y": 340
    },
    {
      "id": 370,
      "name": "Door #11",
      "type": "door",
      "x": 42,
      "y": 406
    },
    {
      "id": 371,
      "name": "Big Door",
      "type": "door",
      "x": 241,
      "y": 343
    }
  ],
  "50402": [
    {
      "id": 372,
      "name": "Box #1",
      "type": "box",
      "x": 365,
      "y": 100
    },
    {
      "id": 373,
      "name": "Box #2",
      "type": "box",
      "x": 395,
      "y": 136
    },
    {
      "id": 374,
      "name": "Box #3",
      "type": "box",
      "x": 366,
      "y": 168
    },
    {
      "id": 375,
      "name": "Box #4",
      "type": "box",
      "x": 126,
      "y": 374
    },
    {
      "id": 376,
      "name": "Entrance",
      "type": "door",
      "x": 138,
      "y": 551
    },
    {
      "id": 377,
      "name": "Exit",
      "type": "door",
      "x": 46,
      "y": 265
    },
    {
      "id": 378,
      "name": "Entrance #2",
      "type": "door",
      "x": 236,
      "y": 390
    },
    {
      "id": 379,
      "name": "Exit #2",
      "type": "door",
      "x": 43,
      "y": 40
    },
    {
      "id": 380,
      "name": "Exit #3",
      "type": "door",
      "x": 539,
      "y": 522
    }
  ],
  "50403": [
    {
      "id": 381,
      "name": "Entrance",
      "type": "door",
      "x": 429,
      "y": 151
    },
    {
      "id": 382,
      "name": "Exit",
      "type": "door",
      "x": 58,
      "y": 23
    }
  ],
  "50404": [
    {
      "id": 383,
      "name": "Box #1",
      "type": "box",
      "x": 412,
      "y": 90
    },
    {
      "id": 384,
      "name": "Box #2",
      "type": "box",
      "x": 236,
      "y": 233
    },
    {
      "id": 385,
      "name": "Box #3",
      "type": "box",
      "x": 60,
      "y": 183
    },
    {
      "id": 386,
      "name": "Box #4",
      "type": "box",
      "x": 268,
      "y": 331
    },
    {
      "id": 387,
      "name": "Box #5",
      "type": "box",
      "x": 269,
      "y": 438
    },
    {
      "id": 388,
      "name": "Box #6",
      "type": "box",
      "x": 221,
      "y": 422
    },
    {
      "id": 389,
      "name": "Entrance",
      "type": "door",
      "x": 398,
      "y": 442
    },
    {
      "id": 390,
      "name": "Lower Exit",
      "type": "door",
      "x": 63,
      "y": 424
    },
    {
      "id": 391,
      "name": "Upper Exit",
      "type": "door",
      "x": 74,
      "y": 43
    }
  ],
  "50405": [
    {
      "id": 392,
      "name": "Box #1",
      "type": "box",
      "x": 25,
      "y": 91
    },
    {
      "id": 393,
      "name": "Box #2",
      "type": "box",
      "x": 28,
      "y": 124
    },
    {
      "id": 394,
      "name": "Box #3",
      "type": "box",
      "x": 154,
      "y": 267
    },
    {
      "id": 395,
      "name": "Box #4",
      "type": "box",
      "x": 41,
      "y": 394
    },
    {
      "id": 396,
      "name": "Entrance",
      "type": "door",
      "x": 286,
      "y": 430
    },
    {
      "id": 397,
      "name": "Exit",
      "type": "door",
      "x": 74,
      "y": 41
    }
  ],
  "50406": [
    {
      "id": 398,
      "name": "Box #1",
      "type": "box",
      "x": 236,
      "y": 72
    },
    {
      "id": 399,
      "name": "Box #2",
      "type": "box",
      "x": 269,
      "y": 75
    },
    {
      "id": 400,
      "name": "Chest #1",
      "type": "chest",
      "x": 368,
      "y": 331
    },
    {
      "id": 401,
      "name": "Entrance",
      "type": "door",
      "x": 62,
      "y": 378
    },
    {
      "id": 402,
      "name": "Entrance #2",
      "type": "door",
      "x": 222,
      "y": 443
    }
  ],
  "50407": [
    {
      "id": 403,
      "name": "Box #1",
      "type": "box",
      "x": 58,
      "y": 74
    },
    {
      "id": 404,
      "name": "Entrance",
      "type": "door",
      "x": 169,
      "y": 242
    }
  ],
  "50408": [
    {
      "id": 405,
      "name": "Box #1",
      "type": "box",
      "x": 26,
      "y": 170
    },
    {
      "id": 406,
      "name": "Box #2",
      "type": "box",
      "x": 41,
      "y": 167
    },
    {
      "id": 407,
      "name": "Box #3",
      "type": "box",
      "x": 102,
      "y": 170
    },
    {
      "id": 408,
      "name": "Box #4",
      "type": "box",
      "x": 121,
      "y": 170
    },
    {
      "id": 409,
      "name": "Entrance",
      "type": "door",
      "x": 76,
      "y": 249
    },
    {
      "id": 410,
      "name": "Exit",
      "type": "door",
      "x": 74,
      "y": 24
    }
  ],
  "50409": [
    {
      "id": 411,
      "name": "Box #1",
      "type": "box",
      "x": 144,
      "y": 203
    },
    {
      "id": 412,
      "name": "Box #2",
      "type": "box",
      "x": 141,
      "y": 171
    },
    {
      "id": 413,
      "name": "Box #3",
      "type": "box",
      "x": 206,
      "y": 88
    },
    {
      "id": 414,
      "name": "Chest #1",
      "type": "chest",
      "x": 143,
      "y": 56
    },
    {
      "id": 415,
      "name": "Exit",
      "type": "door",
      "x": 193,
      "y": 329
    },
    {
      "id": 416,
      "name": "Entrance #3",
      "type": "door",
      "x": 256,
      "y": 364
    },
    {
      "id": 417,
      "name": "Entrance",
      "type": "door",
      "x": 44,
      "y": 298
    },
    {
      "id": 418,
      "name": "Entrance #2",
      "type": "door",
      "x": 48,
      "y": 108
    }
  ],
  "50410": [
    {
      "id": 419,
      "name": "Entrance",
      "type": "door",
      "x": 75,
      "y": 248
    },
    {
      "id": 420,
      "name": "Exit",
      "type": "door",
      "x": 78,
      "y": 24
    }
  ],
  "50411": [
    {
      "id": 421,
      "name": "Entrance",
      "type": "door",
      "x": 76,
      "y": 394
    },
    {
      "id": 422,
      "name": "Exit",
      "type": "door",
      "x": 91,
      "y": 122
    }
  ],
  "50412": [
    {
      "id": 423,
      "name": "Box #1",
      "type": "box",
      "x": 42,
      "y": 60
    },
    {
      "id": 424,
      "name": "Chest #1",
      "type": "chest",
      "x": 201,
      "y": 58
    },
    {
      "id": 425,
      "name": "Box #2",
      "type": "box",
      "x": 412,
      "y": 456
    },
    {
      "id": 426,
      "name": "Entrance",
      "type": "door",
      "x": 239,
      "y": 490
    },
    {
      "id": 427,
      "name": "Exit",
      "type": "door",
      "x": 410,
      "y": 44
    }
  ],
  "50501": [
    {
      "id": 428,
      "name": "Box #1",
      "type": "box",
      "x": 70,
      "y": 53
    },
    {
      "id": 429,
      "name": "Box #2",
      "type": "box",
      "x": 183,
      "y": 56
    },
    {
      "id": 430,
      "name": "Entrance",
      "type": "door",
      "x": 154,
      "y": 182
    },
    {
      "id": 431,
      "name": "Crest",
      "type": "door",
      "x": 119,
      "y": 105
    }
  ],
  "60102": [
    {
      "id": 432,
      "name": "Entrance",
      "type": "door",
      "x": 202,
      "y": 599
    },
    {
      "id": 433,
      "name": "Bottom Right House",
      "type": "door",
      "x": 324,
      "y": 583
    },
    {
      "id": 434,
      "name": "Bottom Left House",
      "type": "door",
      "x": 115,
      "y": 535
    },
    {
      "id": 435,
      "name": "Top Left House",
      "type": "door",
      "x": 100,
      "y": 330
    },
    {
      "id": 436,
      "name": "Middle Right House",
      "type": "door",
      "x": 273,
      "y": 504
    },
    {
      "id": 437,
      "name": "Top Right House",
      "type": "door",
      "x": 292,
      "y": 295
    },
    {
      "id": 438,
      "name": "Rainbow",
      "type": "door",
      "x": 324,
      "y": 89
    }
  ],
  "60103": [
    {
      "id": 439,
      "name": "Entrance",
      "type": "door",
      "x": 170,
      "y": 197
    },
    {
      "id": 440,
      "name": "Stairs",
      "type": "door",
      "x": 40,
      "y": 107
    }
  ],
  "60104": [
    {
      "id": 441,
      "name": "Box #1",
      "type": "box",
      "x": 136,
      "y": 36
    },
    {
      "id": 442,
      "name": "Box #2",
      "type": "box",
      "x": 136,
      "y": 56
    },
    {
      "id": 443,
      "name": "Stairs",
      "type": "door",
      "x": 120,
      "y": 119
    }
  ],
  "60105": [
    {
      "id": 444,
      "name": "Stairs",
      "type": "door",
      "x": 39,
      "y": 57
    },
    {
      "id": 445,
      "name": "Entrance",
      "type": "door",
      "x": 150,
      "y": 229
    }
  ],
  "60106": [
    {
      "id": 446,
      "name": "Box #1",
      "type": "box",
      "x": 39,
      "y": 106
    },
    {
      "id": 447,
      "name": "Stairs",
      "type": "door",
      "x": 37,
      "y": 57
    }
  ],
  "60107": [
    {
      "id": 448,
      "name": "Stairs",
      "type": "door",
      "x": 187,
      "y": 198
    }
  ],
  "60108": [
    {
      "id": 449,
      "name": "Entrance",
      "type": "door",
      "x": 155,
      "y": 167
    },
    {
      "id": 450,
      "name": "Stairs",
      "type": "door",
      "x": 230,
      "y": 59
    }
  ],
  "60109": [
    {
      "id": 451,
      "name": "Box #1",
      "type": "box",
      "x": 39,
      "y": 53
    },
    {
      "id": 452,
      "name": "Box #2",
      "type": "box",
      "x": 71,
      "y": 56
    },
    {
      "id": 453,
      "name": "Entrance",
      "type": "door",
      "x": 56,
      "y": 136
    },
    {
      "id": 454,
      "name": "Crest",
      "type": "door",
      "x": 57,
      "y": 87
    }
  ],
  "60110": [
    {
      "id": 455,
      "name": "Entrance",
      "type": "door",
      "x": 121,
      "y": 168
    },
    {
      "id": 456,
      "name": "Stairs",
      "type": "door",
      "x": 26,
      "y": 74
    }
  ],
  "60111": [
    {
      "id": 457,
      "name": "Stairs",
      "type": "door",
      "x": 90,
      "y": 87
    },
    {
      "id": 458,
      "name": "Crest",
      "type": "door",
      "x": 56,
      "y": 105
    }
  ],
  "60203": [
    {
      "id": 459,
      "name": "Entrance",
      "type": "door",
      "x": 184,
      "y": 218
    },
    {
      "id": 460,
      "name": "Crest",
      "type": "door",
      "x": 393,
      "y": 171
    },
    {
      "id": 461,
      "name": "Crest",
      "type": "door",
      "x": 920,
      "y": 793
    },
    {
      "id": 743,
      "name": "Crest #2",
      "type": "door",
      "x": 920,
      "y": 793
    },
    {
      "id": 744,
      "name": "Crest #3",
      "type": "door",
      "x": 133,
      "y": 838
    }
  ],
  "60205": [
    {
      "id": 462,
      "name": "Box #1",
      "type": "box",
      "x": 105,
      "y": 165
    },
    {
      "id": 745,
      "name": "Crest",
      "type": "door",
      "x": 105,
      "y": 115
    }
  ],
  "60206": [
    {
      "id": 463,
      "name": "Box #1",
      "type": "box",
      "x": 136,
      "y": 149
    },
    {
      "id": 746,
      "name": "Crest",
      "type": "door",
      "x": 102,
      "y": 117
    }
  ],
  "60207": [
    {
      "id": 464,
      "name": "Box #1",
      "type": "box",
      "x": 120,
      "y": 170
    },
    {
      "id": 465,
      "name": "Box #2",
      "type": "box",
      "x": 122,
      "y": 84
    },
    {
      "id": 747,
      "name": "Crest",
      "type": "door",
      "x": 104,
      "y": 119
    }
  ],
  "60301": [
    {
      "id": 748,
      "name": "Entrance",
      "type": "door",
      "x": 269,
      "y": 527
    },
    {
      "id": 749,
      "name": "Exit",
      "type": "door",
      "x": 233,
      "y": 49
    },
    {
      "id": 750,
      "name": "Box #1",
      "type": "box",
      "x": 54,
      "y": 187
    },
    {
      "id": 751,
      "name": "Box #2",
      "type": "box",
      "x": 56,
      "y": 363
    },
    {
      "id": 752,
      "name": "Box #3",
      "type": "box",
      "x": 247,
      "y": 269
    },
    {
      "id": 753,
      "name": "Box #4",
      "type": "box",
      "x": 373,
      "y": 314
    }
  ],
  "60302": [
    {
      "id": 466,
      "name": "Chest #1",
      "type": "chest",
      "x": 472,
      "y": 239
    },
    {
      "id": 467,
      "name": "Box #1",
      "type": "box",
      "x": 440,
      "y": 201
    },
    {
      "id": 468,
      "name": "Box #2",
      "type": "box",
      "x": 104,
      "y": 422
    },
    {
      "id": 469,
      "name": "Box #3",
      "type": "box",
      "x": 437,
      "y": 425
    },
    {
      "id": 754,
      "name": "Door #1",
      "type": "door",
      "x": 200,
      "y": 298
    },
    {
      "id": 755,
      "name": "Door #2",
      "type": "door",
      "x": 454,
      "y": 335
    },
    {
      "id": 756,
      "name": "Door #3",
      "type": "door",
      "x": 230,
      "y": 79
    },
    {
      "id": 757,
      "name": "Door #4",
      "type": "door",
      "x": 70,
      "y": 142
    }
  ],
  "60303": [
    {
      "id": 470,
      "name": "Box #1",
      "type": "box",
      "x": 196,
      "y": 106
    },
    {
      "id": 471,
      "name": "Box #2",
      "type": "box",
      "x": 182,
      "y": 106
    },
    {
      "id": 758,
      "name": "Entrance",
      "type": "door",
      "x": 404,
      "y": 235
    },
    {
      "id": 759,
      "name": "Exit",
      "type": "door",
      "x": 425,
      "y": 65
    }
  ],
  "60304": [
    {
      "id": 472,
      "name": "Box #1",
      "type": "box",
      "x": 183,
      "y": 493
    },
    {
      "id": 473,
      "name": "Box #2",
      "type": "box",
      "x": 216,
      "y": 444
    },
    {
      "id": 474,
      "name": "Box #3",
      "type": "box",
      "x": 297,
      "y": 443
    },
    {
      "id": 475,
      "name": "Box #4",
      "type": "box",
      "x": 137,
      "y": 605
    },
    {
      "id": 760,
      "name": "Door #1",
      "type": "door",
      "x": 265,
      "y": 494
    },
    {
      "id": 761,
      "name": "Door #2",
      "type": "door",
      "x": 55,
      "y": 334
    },
    {
      "id": 762,
      "name": "Door #3",
      "type": "door",
      "x": 245,
      "y": 270
    },
    {
      "id": 763,
      "name": "Door #4",
      "type": "door",
      "x": 458,
      "y": 273
    },
    {
      "id": 764,
      "name": "Door #5",
      "type": "door",
      "x": 358,
      "y": 44
    }
  ],
  "60305": [
    {
      "id": 476,
      "name": "Box #1",
      "type": "box",
      "x": 232,
      "y": 94
    },
    {
      "id": 765,
      "name": "Entrance",
      "type": "door",
      "x": 298,
      "y": 381
    },
    {
      "id": 766,
      "name": "Exit",
      "type": "door",
      "x": 73,
      "y": 351
    }
  ],
  "60306": [
    {
      "id": 477,
      "name": "Box #1",
      "type": "box",
      "x": 106,
      "y": 301
    },
    {
      "id": 478,
      "name": "Box #2",
      "type": "box",
      "x": 106,
      "y": 286
    },
    {
      "id": 479,
      "name": "Box #3",
      "type": "box",
      "x": 313,
      "y": 474
    },
    {
      "id": 480,
      "name": "Box #4",
      "type": "box",
      "x": 279,
      "y": 506
    },
    {
      "id": 767,
      "name": "Door #1",
      "type": "door",
      "x": 103,
      "y": 412
    },
    {
      "id": 768,
      "name": "Door #2",
      "type": "door",
      "x": 200,
      "y": 446
    },
    {
      "id": 769,
      "name": "Door #3",
      "type": "door",
      "x": 296,
      "y": 443
    },
    {
      "id": 770,
      "name": "Door #4",
      "type": "door",
      "x": 104,
      "y": 351
    },
    {
      "id": 771,
      "name": "Door #5",
      "type": "door",
      "x": 168,
      "y": 317
    },
    {
      "id": 772,
      "name": "Door #6",
      "type": "door",
      "x": 296,
      "y": 157
    }
  ],
  "60307": [
    {
      "id": 481,
      "name": "Box #1",
      "type": "box",
      "x": 86,
      "y": 190
    },
    {
      "id": 482,
      "name": "Box #2",
      "type": "box",
      "x": 296,
      "y": 153
    },
    {
      "id": 773,
      "name": "Entrance #1",
      "type": "door",
      "x": 119,
      "y": 397
    },
    {
      "id": 774,
      "name": "Entrance #2",
      "type": "door",
      "x": 199,
      "y": 395
    },
    {
      "id": 775,
      "name": "Entrance #3",
      "type": "door",
      "x": 310,
      "y": 461
    },
    {
      "id": 776,
      "name": "Entrance #4",
      "type": "door",
      "x": 151,
      "y": 172
    }
  ],
  "60308": [
    {
      "id": 483,
      "name": "Box #1",
      "type": "box",
      "x": 54,
      "y": 138
    },
    {
      "id": 484,
      "name": "Box #2",
      "type": "box",
      "x": 86,
      "y": 137
    },
    {
      "id": 485,
      "name": "Box #3",
      "type": "box",
      "x": 170,
      "y": 364
    },
    {
      "id": 486,
      "name": "Box #4",
      "type": "box",
      "x": 218,
      "y": 360
    },
    {
      "id": 777,
      "name": "Entrance",
      "type": "door",
      "x": 199,
      "y": 269
    },
    {
      "id": 778,
      "name": "Exit",
      "type": "door",
      "x": 201,
      "y": 44
    }
  ],
  "60401": [
    {
      "id": 487,
      "name": "Box #1",
      "type": "box",
      "x": 52,
      "y": 150
    },
    {
      "id": 488,
      "name": "Box #2",
      "type": "box",
      "x": 69,
      "y": 151
    },
    {
      "id": 489,
      "name": "Box #3",
      "type": "box",
      "x": 83,
      "y": 151
    },
    {
      "id": 490,
      "name": "Box #4",
      "type": "box",
      "x": 123,
      "y": 249
    },
    {
      "id": 779,
      "name": "Entrance",
      "type": "door",
      "x": 209,
      "y": 425
    },
    {
      "id": 780,
      "name": "Stairs #1",
      "type": "door",
      "x": 265,
      "y": 391
    },
    {
      "id": 781,
      "name": "Stairs #2",
      "type": "door",
      "x": 58,
      "y": 263
    },
    {
      "id": 782,
      "name": "Stairs #3",
      "type": "door",
      "x": 325,
      "y": 185
    }
  ],
  "60402": [
    {
      "id": 491,
      "name": "Box #1",
      "type": "box",
      "x": 326,
      "y": 201
    },
    {
      "id": 492,
      "name": "Box #2",
      "type": "box",
      "x": 359,
      "y": 204
    },
    {
      "id": 783,
      "name": "Stairs #1",
      "type": "door",
      "x": 57,
      "y": 264
    },
    {
      "id": 784,
      "name": "Stairs #2",
      "type": "door",
      "x": 198,
      "y": 232
    },
    {
      "id": 785,
      "name": "Stairs #3",
      "type": "door",
      "x": 278,
      "y": 375
    },
    {
      "id": 786,
      "name": "Stairs #4",
      "type": "door",
      "x": 71,
      "y": 168
    }
  ],
  "60403": [
    {
      "id": 493,
      "name": "Box #1",
      "type": "box",
      "x": 343,
      "y": 230
    },
    {
      "id": 494,
      "name": "Box #2",
      "type": "box",
      "x": 376,
      "y": 234
    },
    {
      "id": 495,
      "name": "Box #3",
      "type": "box",
      "x": 167,
      "y": 392
    },
    {
      "id": 787,
      "name": "Stairs #4",
      "type": "door",
      "x": 232,
      "y": 390
    },
    {
      "id": 788,
      "name": "Stairs #3",
      "type": "door",
      "x": 74,
      "y": 233
    },
    {
      "id": 789,
      "name": "Stairs #1",
      "type": "door",
      "x": 199,
      "y": 215
    },
    {
      "id": 790,
      "name": "Stairs #2",
      "type": "door",
      "x": 329,
      "y": 167
    }
  ],
  "60404": [
    {
      "id": 496,
      "name": "Box #1",
      "type": "box",
      "x": 183,
      "y": 138
    },
    {
      "id": 497,
      "name": "Box #2",
      "type": "box",
      "x": 231,
      "y": 139
    },
    {
      "id": 498,
      "name": "Chest #1",
      "type": "chest",
      "x": 393,
      "y": 236
    },
    {
      "id": 791,
      "name": "Stairs #1",
      "type": "door",
      "x": 199,
      "y": 378
    },
    {
      "id": 792,
      "name": "Stairs #2",
      "type": "door",
      "x": 72,
      "y": 295
    },
    {
      "id": 793,
      "name": "Stairs #3",
      "type": "door",
      "x": 72,
      "y": 186
    },
    {
      "id": 794,
      "name": "Stairs #4",
      "type": "door",
      "x": 307,
      "y": 139
    }
  ],
  "60405": [
    {
      "id": 499,
      "name": "Box #1",
      "type": "box",
      "x": 344,
      "y": 200
    },
    {
      "id": 500,
      "name": "Box #2",
      "type": "box",
      "x": 329,
      "y": 310
    },
    {
      "id": 795,
      "name": "Stairs #1",
      "type": "door",
      "x": 216,
      "y": 360
    },
    {
      "id": 796,
      "name": "Stairs #2",
      "type": "door",
      "x": 311,
      "y": 118
    },
    {
      "id": 797,
      "name": "Stairs #3",
      "type": "door",
      "x": 105,
      "y": 117
    },
    {
      "id": 798,
      "name": "Stairs #4",
      "type": "door",
      "x": 104,
      "y": 260
    }
  ],
  "60406": [
    {
      "id": 501,
      "name": "Chest #1",
      "type": "chest",
      "x": 136,
      "y": 374
    },
    {
      "id": 502,
      "name": "Box #1",
      "type": "box",
      "x": 281,
      "y": 391
    },
    {
      "id": 799,
      "name": "Stairs #1",
      "type": "door",
      "x": 279,
      "y": 374
    },
    {
      "id": 800,
      "name": "Stairs #2",
      "type": "door",
      "x": 312,
      "y": 122
    },
    {
      "id": 801,
      "name": "Stairs #3",
      "type": "door",
      "x": 106,
      "y": 118
    },
    {
      "id": 802,
      "name": "Stairs #4",
      "type": "door",
      "x": 107,
      "y": 229
    }
  ],
  "60407": [
    {
      "id": 503,
      "name": "Chest #1",
      "type": "chest",
      "x": 266,
      "y": 67
    },
    {
      "id": 803,
      "name": "Stairs #1",
      "type": "door",
      "x": 230,
      "y": 338
    },
    {
      "id": 804,
      "name": "Stairs #2",
      "type": "door",
      "x": 326,
      "y": 369
    },
    {
      "id": 805,
      "name": "Stairs #3",
      "type": "door",
      "x": 328,
      "y": 116
    }
  ],
  "60501": [
    {
      "id": 504,
      "name": "Box #1",
      "type": "box",
      "x": 374,
      "y": 438
    },
    {
      "id": 505,
      "name": "Box #2",
      "type": "box",
      "x": 886,
      "y": 442
    },
    {
      "id": 806,
      "name": "Entrance",
      "type": "door",
      "x": 99,
      "y": 649
    }
  ],
  "60601": [
    {
      "id": 506,
      "name": "Box #1",
      "type": "box",
      "x": 437,
      "y": 425
    },
    {
      "id": 507,
      "name": "Box #2",
      "type": "box",
      "x": 647,
      "y": 422
    },
    {
      "id": 807,
      "name": "Entrance",
      "type": "door",
      "x": 150,
      "y": 189
    },
    {
      "id": 808,
      "name": "Exit",
      "type": "door",
      "x": 849,
      "y": 192
    }
  ],
  "60701": [
    {
      "id": 809,
      "name": "Crest",
      "type": "door",
      "x": 209,
      "y": 218
    },
    {
      "id": 810,
      "name": "Ship",
      "type": "door",
      "x": 205,
      "y": 10
    }
  ],
  "60801": [
    {
      "id": 508,
      "name": "Box #1",
      "type": "box",
      "x": 151,
      "y": 56
    },
    {
      "id": 811,
      "name": "Entrance",
      "type": "door",
      "x": 201,
      "y": 421
    },
    {
      "id": 812,
      "name": "Crest",
      "type": "door",
      "x": 55,
      "y": 324
    }
  ],
  "60901": [
    {
      "id": 509,
      "name": "Box #1",
      "type": "box",
      "x": 316,
      "y": 51
    },
    {
      "id": 813,
      "name": "Crest",
      "type": "door",
      "x": 231,
      "y": 56
    },
    {
      "id": 814,
      "name": "Entrance",
      "type": "door",
      "x": 217,
      "y": 375
    }
  ],
  "61001": [
    {
      "id": 510,
      "name": "Box #1",
      "type": "box",
      "x": 170,
      "y": 231
    },
    {
      "id": 815,
      "name": "Entrance",
      "type": "door",
      "x": 168,
      "y": 376
    }
  ],
  "70101": [
    {
      "id": 816,
      "name": "Entrance",
      "type": "door",
      "x": 57,
      "y": 549
    },
    {
      "id": 817,
      "name": "Sand Door",
      "type": "door",
      "x": 58,
      "y": 423
    },
    {
      "id": 818,
      "name": "Water Door",
      "type": "door",
      "x": 58,
      "y": 299
    },
    {
      "id": 819,
      "name": "Fire Door",
      "type": "door",
      "x": 55,
      "y": 171
    },
    {
      "id": 820,
      "name": "Wind Door",
      "type": "door",
      "x": 55,
      "y": 39
    }
  ],
  "70102": [
    {
      "id": 511,
      "name": "Box #1",
      "type": "box",
      "x": 319,
      "y": 367
    },
    {
      "id": 512,
      "name": "Box #2",
      "type": "box",
      "x": 497,
      "y": 510
    },
    {
      "id": 821,
      "name": "Side Entrance",
      "type": "door",
      "x": 448,
      "y": 640
    },
    {
      "id": 822,
      "name": "Entrance",
      "type": "door",
      "x": 319,
      "y": 702
    },
    {
      "id": 823,
      "name": "Exit",
      "type": "door",
      "x": 402,
      "y": 318
    }
  ],
  "70103": [
    {
      "id": 513,
      "name": "Box #1",
      "type": "box",
      "x": 183,
      "y": 230
    },
    {
      "id": 514,
      "name": "Box #2",
      "type": "box",
      "x": 565,
      "y": 264
    },
    {
      "id": 515,
      "name": "Box #3",
      "type": "box",
      "x": 552,
      "y": 489
    },
    {
      "id": 516,
      "name": "Box #4",
      "type": "box",
      "x": 105,
      "y": 455
    },
    {
      "id": 824,
      "name": "Entrance",
      "type": "door",
      "x": 313,
      "y": 661
    }
  ],
  "70104": [
    {
      "id": 517,
      "name": "Box #1",
      "type": "box",
      "x": 341,
      "y": 309
    },
    {
      "id": 518,
      "name": "Box #2",
      "type": "box",
      "x": 358,
      "y": 311
    },
    {
      "id": 519,
      "name": "Box #3",
      "type": "box",
      "x": 341,
      "y": 490
    },
    {
      "id": 520,
      "name": "Box #4",
      "type": "box",
      "x": 358,
      "y": 486
    },
    {
      "id": 825,
      "name": "Entrance",
      "type": "door",
      "x": 312,
      "y": 615
    }
  ],
  "70105": [
    {
      "id": 521,
      "name": "Box #1",
      "type": "box",
      "x": 56,
      "y": 183
    },
    {
      "id": 522,
      "name": "Box #2",
      "type": "box",
      "x": 598,
      "y": 392
    },
    {
      "id": 826,
      "name": "Entrance",
      "type": "door",
      "x": 329,
      "y": 614
    }
  ],
  "70106": [
    {
      "id": 523,
      "name": "Chest #1",
      "type": "chest",
      "x": 41,
      "y": 229
    },
    {
      "id": 524,
      "name": "Chest #2",
      "type": "chest",
      "x": 168,
      "y": 102
    },
    {
      "id": 525,
      "name": "Chest #3",
      "type": "chest",
      "x": 247,
      "y": 102
    },
    {
      "id": 526,
      "name": "Chest #4",
      "type": "chest",
      "x": 358,
      "y": 233
    },
    {
      "id": 827,
      "name": "Entrance",
      "type": "door",
      "x": 200,
      "y": 391
    },
    {
      "id": 828,
      "name": "Exit",
      "type": "door",
      "x": 207,
      "y": 82
    }
  ],
  "70107": [
    {
      "id": 829,
      "name": "Entrance",
      "type": "door",
      "x": 199,
      "y": 440
    }
  ],
  "70201": [
    {
      "id": 527,
      "name": "Box #1",
      "type": "box",
      "x": 151,
      "y": 166
    },
    {
      "id": 528,
      "name": "Box #2",
      "type": "box",
      "x": 168,
      "y": 423
    },
    {
      "id": 529,
      "name": "Box #3",
      "type": "box",
      "x": 200,
      "y": 885
    },
    {
      "id": 830,
      "name": "Entrance",
      "type": "door",
      "x": 361,
      "y": 598
    },
    {
      "id": 831,
      "name": "Stairs #1",
      "type": "door",
      "x": 200,
      "y": 710
    },
    {
      "id": 832,
      "name": "Stairs #2",
      "type": "door",
      "x": 328,
      "y": 536
    },
    {
      "id": 833,
      "name": "Stairs #3",
      "type": "door",
      "x": 72,
      "y": 502
    },
    {
      "id": 834,
      "name": "Stairs #4",
      "type": "door",
      "x": 136,
      "y": 104
    }
  ],
  "70202": [
    {
      "id": 530,
      "name": "Box #1",
      "type": "box",
      "x": 72,
      "y": 56
    },
    {
      "id": 531,
      "name": "Box #2",
      "type": "box",
      "x": 186,
      "y": 233
    },
    {
      "id": 532,
      "name": "Box #3",
      "type": "box",
      "x": 198,
      "y": 518
    },
    {
      "id": 533,
      "name": "Chest #1",
      "type": "chest",
      "x": 105,
      "y": 762
    },
    {
      "id": 835,
      "name": "Stairs #1",
      "type": "door",
      "x": 184,
      "y": 759
    },
    {
      "id": 836,
      "name": "Stairs #",
      "type": "door",
      "x": 183,
      "y": 665
    },
    {
      "id": 837,
      "name": "Stairs #3",
      "type": "door",
      "x": 325,
      "y": 536
    },
    {
      "id": 838,
      "name": "Stairs #4",
      "type": "door",
      "x": 182,
      "y": 551
    },
    {
      "id": 839,
      "name": "Stairs #5",
      "type": "door",
      "x": 53,
      "y": 506
    },
    {
      "id": 840,
      "name": "Stairs #6",
      "type": "door",
      "x": 186,
      "y": 360
    },
    {
      "id": 841,
      "name": "Stairs #7",
      "type": "door",
      "x": 151,
      "y": 97
    },
    {
      "id": 842,
      "name": "Stairs #8",
      "type": "door",
      "x": 187,
      "y": 146
    },
    {
      "id": 843,
      "name": "Stairs #9",
      "type": "door",
      "x": 298,
      "y": 104
    }
  ],
  "70203": [
    {
      "id": 534,
      "name": "Box #1",
      "type": "box",
      "x": 123,
      "y": 247
    },
    {
      "id": 535,
      "name": "Box #2",
      "type": "box",
      "x": 118,
      "y": 279
    },
    {
      "id": 536,
      "name": "Box #3",
      "type": "box",
      "x": 119,
      "y": 646
    },
    {
      "id": 537,
      "name": "Box #4",
      "type": "box",
      "x": 249,
      "y": 651
    },
    {
      "id": 844,
      "name": "Stairs #1",
      "type": "door",
      "x": 182,
      "y": 762
    },
    {
      "id": 845,
      "name": "Stairs #2",
      "type": "door",
      "x": 183,
      "y": 554
    },
    {
      "id": 846,
      "name": "Stairs #3",
      "type": "door",
      "x": 187,
      "y": 374
    },
    {
      "id": 847,
      "name": "Stairs #4",
      "type": "door",
      "x": 181,
      "y": 134
    },
    {
      "id": 848,
      "name": "Stairs #5",
      "type": "door",
      "x": 295,
      "y": 121
    }
  ],
    "60408": [
    {
      "id": 594,
      "name": "Entrance",
      "type": "door",
      "x": 143,
      "y": 476
    },
    {
      "id": 595,
      "name": "Exit",
      "type": "door",
      "x": 143,
      "y": 88
    }
  ],
    "60409": [
    {
      "id": 596,
      "name": "Entrance",
      "type": "door",
      "x": 143,
      "y": 476
    },
    {
      "id": 597,
      "name": "Exit",
      "type": "door",
      "x": 143,
      "y": 88
    }
  ],
    "60410": [
    {
      "id": 598,
      "name": "Entrance",
      "type": "door",
      "x": 143,
      "y": 476
    },
    {
      "id": 599,
      "name": "Exit",
      "type": "door",
      "x": 143,
      "y": 88
    }
  ]
};